### ISSUE TITLE
🙋‍♂️請問可以增加 ㄅㄆㄇㄈ注音符號的鍵位嗎？

### ISSUE THREAD

**Issue by trevim99** [BlueSky-07/React-Keyboard-UI#1]
您好
 一 多謝開發 小鶴雙拼 的學習系統及資源，受益良多🙏🙏🙏

我想用 React-keyboard-UI 增加ㄅㄆㄇㄈ注音符號+小鶴雙拼的鍵位圖(樣式）
可是試了好久，做不出來

![小鶴雙拼ㄅㄆㄇ](https://github.com/user-attachments/assets/f3640c03-53fb-4dd9-b76b-d33ed4921348)

請問可以增加 React-keyboard-UI 的操作說明？ 謝謝

二 https://api.ihint.me/shuang/ 請問可以增加 ㄅㄆㄇㄈ注音符號+小鶴雙拼的鍵位圖(樣式） 嗎？

ㄅ, ㄆ, ㄇ, ㄈ, ㄉ, ㄊ, ㄋ, ㄌ, ㄍ, ㄎ, ㄏ, ㄐ, ㄑ, ㄒ, ㄓ, ㄔ, ㄕ, ㄖ, ㄗ, ㄘ, ㄙ, ㄧ, ㄨ, ㄩ, ㄚ, ㄛ, ㄜ, ㄝ, ㄞ, ㄟ, ㄠ, ㄡ, ㄢ, ㄣ, ㄤ, ㄥ, ㄦ

注音符號對照表可參上圖

謝謝您🙏🙏🙏

註： 附圖我是用 keyboard-layout-editor 製作的

http://www.keyboard-layout-editor.com/#/gists/1d2f78e74b50dc253dc72272e9e90184

**Comment by BlueSky-07** [comment]
这个项目当初做得太复杂了，现在不再维护了，后续我会把这个仓库归档掉。
关于在双拼练习项目里添加注音符号的建议，现在的键位图设计里没有放置除了zh/ch/sh以外韵母的例子。
如果后续添加注音符号的话，会考虑在右上角放上声母，下面放韵母，左上角的英文字母保留，但例字不会放进去。

**Comment by BlueSky-07** [comment]
在当前仓库归档后，如需继续讨论，在这里继续：
https://github.com/BlueSky-07/Shuang/issues/43
